apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardian-system

commonLabels:
  app.kubernetes.io/part-of: zero-day-guardian

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secrets.yaml
  - crd/guardianpolicy-crd.yaml
  - networkpolicy-isolation.yaml
  - daemonset.yaml
  - operator-deployment.yaml
