apiVersion: v1
kind: Namespace
metadata:
  name: guardian-system
  labels:
    app.kubernetes.io/name: zero-day-guardian
    app.kubernetes.io/part-of: zero-day-guardian
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
