apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardian-monitor
  namespace: guardian-system
  labels:
    app.kubernetes.io/name: zero-day-guardian
    app.kubernetes.io/component: monitor
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardian-operator
  namespace: guardian-system
  labels:
    app.kubernetes.io/name: zero-day-guardian
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
